{% set version = "1.0.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-n2r
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/N2R_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/N2R/N2R_{{ version }}.tar.gz
  sha256: 59324daea86f2763ca637fef99c553702507b9348ee84c22efba2e333ca07d2d

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - _openmp_mutex                # [linux]
    - llvm-openmp                  # [osx]
    - r-base
    - r-matrix
    - r-rcpp >=1.0.4
    - r-rcppeigen
    - r-rcppspdlog
  run:
    - _openmp_mutex                # [linux]
    - llvm-openmp                  # [osx]
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-matrix
    - r-rcpp >=1.0.4
    - r-rcppeigen
    - r-rcppspdlog

test:
  commands:
    - $R -e "library('N2R')"           # [not win]
    - "\"%R%\" -e \"library('N2R')\""  # [win]

about:
  home: https://github.com/kharchenkolab/N2R
  license: Apache-2.0
  summary: Implements methods to perform fast approximate K-nearest neighbor search on input matrix. Algorithm based on the 'N2' implementation of an approximate nearest neighbor search using hierarchical  Navigable Small World (NSW) graphs. The original algorithm is described in "Efficient and Robust Approximate Nearest
    Neighbor Search Using Hierarchical Navigable Small World Graphs", Y. Malkov and D. Yashunin, <doi:10.1109/TPAMI.2018.2889473>, <arXiv:1603.09320>.
  license_family: APACHE
  license_file:
    - LICENSE-2.0.txt

extra:
  recipe-maintainers:
    - conda-forge/r
